### ISSUE TITLE
What is SLACK_HOOK_URL ?

### ISSUE THREAD

**Issue by katagen** [lutraconsulting/mergin#11]
I can't find what I should put in the docker-compose at the line "SLACK_HOOK_URL=fixme"? Where can I find information for this?

And what does it do?

**Comment by dracic** [comment]
If you have slack account you can send messages from Mergin using incoming webhooks:

[https://api.slack.com/messaging/webhooks](url)

You can omit this line if you don't want to use Slack

**Comment by katagen** [comment]
Thank you for the answer!

**Comment by poVoq** [comment]
Is this only for admin notifications or can the recipient be configured on user basis?

I have another chat system that accepts Slack like webhooks and it would be cool if users could add their channel to be notified.

**Comment by PeterPetrik** [comment]
Please open another ticket for the the support for your provider

**Comment by poVoq** [comment]
Is selfhosted and looks the same as Slack from the outside.
