### ISSUE TITLE
Authentification failed on Iphone with a custom mergin server

### ISSUE THREAD

**Issue by arno974** [lutraconsulting/mergin#19]
While the authentification works on an iPhone using the public mergin server it does not work using a "private" mergin server  (a mergin server on my own server). I have tried to do it on two different iPhone and same result : "Incorrect username or password". The same credentials works when using an android phone.

Have you ever noticed such problems ?

**Comment by saberraz** [comment]
Could you try to add / at the end of your link:
https://github.com/lutraconsulting/mergin/issues/8#issuecomment-871625539

**Comment by arno974** [comment]
Thanks for your solution, the error was probably due to the slash and the fact that we must click again on the pencil !
It is all good now !
