### ISSUE TITLE
Impossible to get a project list in Input when deploying outside docker 

### ISSUE THREAD

**Issue by cazitouni** [lutraconsulting/mergin#24]
Hello,

I Encounter a problem trying to deploy the server outside the docker container following the procedure in developpement.md.
I can deploy everything I can log in in the web client and in the Qgis plugin, I can also upload and retrieve a project from the web or the plugin.
But when it comes to the mobile client The app seem to be unable to get the project list from the server. 
Server side I only got a ping 200 and no error whatsoever. 

If i use the dockerized server on the same config everything works fine. (outside other issues already discussed on github)

Thansk you for your consideration.

**Comment by wonder-sk** [comment]
Great to hear it works.

For the `--legacy-peer-deps` argument - we'll have a look at that, no need to open a new issue... Cheers!
