### ISSUE TITLE
Error during app creation on docker - Linux

### ISSUE THREAD

**Issue by l2kuami** [lutraconsulting/mergin#26]
Hello, 
Thank for the work done... Congratulations... 

I am facing some issue when deploying Mergin server on my server 

Here is the error : standard_init_linux.go:219: exec user process caused: exec format error

Is there any way to bypass it? 

Regards.

**Comment by PeterPetrik** [comment]
Hi,

unfortunately this is too little information to help. Could you join our community chat merginmaps.com/community/join and we can discuss there?
