### ISSUE TITLE
Input doesn't support multiple-selection field from a QGIS project ?

### ISSUE THREAD

**Issue by LeiHeadlandArc** [lutraconsulting/mergin#29]
Hi,
I set up a multiple selection field in a layer in my QGIS project by the widget 'Value relation', and it would shows like {"valueA", "valueB"} as a label when I select more than one value. Therefore I use a expression for the value in the label as **replace(replace(replace("Action", '{"', ''), '"}', ''), '","', '\n')**
which can remove the {} and "" in the label, also can make the value show as a list, each value has its own line. It works well in my QGIS project. And when I synchronized it to my Input (on Ipad or Phone), it shows the same format label.

However, if I change the field value on Input (multi-selected in that field for a feature), then the label will back to the original format, which with the {""}. How can I solve this problem?
The image below shows the problem I described, the orange box at the left up corner is the correct format, and the problem one is at the middle (also a orange box)

Thank you,
Lei
![image](https://user-images.githubusercontent.com/101812148/158821354-f5c321de-7241-4283-b35f-97c86ed17473.png)

**Comment by saberraz** [comment]
Hi, you should use: `replace(replace(replace("Action",array('{"','{'),array('','')), array('"}','}'),array('','')),array('","',','),array('\n','\n'))` instead.
