### ISSUE TITLE
Data types with unpredictable results in the UI of INPUT

### ISSUE THREAD

**Issue by KajFRasmussen** [lutraconsulting/mergin#3]
We have been testing working via Mergin/Input on archaeological sites (and YAY what a nice product), but are presently kicking at a "stone" that wont budge it seems... We have been using boolean and date as formats for some data collection tables, and for the first three cases it worked just fine in the Input interface, giving a toggle switch for boolean fields, and a date field with a calendar pop-up for date fields. 

Alas now every single time we try this the fields are only shown as regular data field (text input box).
We have turned the "stone" in every angle we can think of: 
Copying GPKG files that work to the new case (accepting the "false" name)
Saving copies of GPKG files that DO work, creating new GPKG files that sadly DONT
Moving affected the layers to projects without the problem
Creating new layers in projects without the problem, which do also not work
Avoiding spaces  and special characters in file and field naming.

-but all to no avail...

The data types work fine in Qgis 3.16 and 3.18.1 (check box for boolean and calendar pop up for date format fields).

Is there a bug in Input itself?

I have made a public demo of the error under my user name: Datafieldtype

SIMKFR

**Comment by KajFRasmussen** [comment]
![Screenshot_20210422_095450_uk co lutraconsulting](https://user-images.githubusercontent.com/77663465/115677594-ecc55a80-a350-11eb-84c7-8428bb9f40dd.jpg)
![Screenshot_20210422_095313_uk co lutraconsulting](https://user-images.githubusercontent.com/77663465/115677600-edf68780-a350-11eb-897d-109af9aece7a.jpg)

**Comment by saberraz** [comment]
This is an Input issue and you can track it here https://github.com/lutraconsulting/input/issues/1464
Mergin is the syncing, storage and web interface.
