### ISSUE TITLE
Connection with Input

### ISSUE THREAD

**Issue by katagen** [lutraconsulting/mergin#8]
Hello,
I was able to connect at mergin.mydomain.ch with different profils. I'm also able to connect on the "mergin plugin" on QGIS with different users.

But on Input, it always says "invalid user name or password"?

I don't know if it is a Mergin or an Input problem!

**Comment by dracic** [comment]
Try to put "/" at the end of custom Mergin URL in Input

**Comment by katagen** [comment]
It’s still saying « invalid user name or password »!

**Comment by katagen** [comment]
I’m behind a reverse proxy, but it works on mergin.mydomain.ch and on mergin plugin for Qgis!?!

**Comment by katagen** [comment]
I found: need http:// at the beginning and / at the end!

**Comment by nicogodet** [comment]
I still have this issue
OK in browser with ipv4 and ipv6
OK in Qgis
NOK in Input

**Comment by katagen** [comment]
Did you validate the new address by clicking on the pencil icon? I noticed that before that, it still try to connect to public.cloudmergin.com!

**Comment by nicogodet** [comment]
@katagen Genius ! Thanks.

**Comment by dracic** [comment]
I think pencil/checkmark icons for some reason are not intuitive enough. Even now when I now the thing, i have to think twice...

**Comment by nicogodet** [comment]
We type our custom server, press Ok on keyboard and we think it's enough.
But no, you need to press on pencil again to validate.

**Comment by wonder-sk** [comment]
Agreed it is confusing. We have plans to move the URL configuration to Settings page and that should also fix the usability issues, however that will require some more changes under the hood (currently you can't access Settings before opening a project first)... I have created a ticket in Input for that - https://github.com/lutraconsulting/input/issues/1544
